### ISSUE TITLE
Formatting for proper markdown

### ISSUE THREAD

**Issue by phlash** [ChaosInTheVoid/TheRules#1]
At present this file doesn't look great as github flavour markdown, happy to fix it if you like :grin: ?

**Comment by ChaosInTheVoid** [comment]
Feel free, bit busy lol

Sent from my iPhone

On 8 Oct 2023, at 09:50, Phil Ashby ***@***.***> wrote:

﻿

At present this file doesn't look great as github flavour markdown, happy to fix it if you like 😁 ?
